// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOU9abGVPM_dfLbEkqlXmNXXN_gxZssus',
    appId: '1:1000701991568:web:6263df987fc33d985b9615',
    messagingSenderId: '1000701991568',
    projectId: 'expense-tracker-343a3',
    authDomain: 'expense-tracker-343a3.firebaseapp.com',
    storageBucket: 'expense-tracker-343a3.appspot.com',
    measurementId: 'G-2C4WX5C1R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYslDRqAXWi_G7ur-oWpyEvgLjEvjurp0',
    appId: '1:1000701991568:android:e45f686bcb3c13875b9615',
    messagingSenderId: '1000701991568',
    projectId: 'expense-tracker-343a3',
    storageBucket: 'expense-tracker-343a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGxEHNPllFoPGSQZyKdf5tvnODsLxQyfc',
    appId: '1:1000701991568:ios:54b2dde1db01ecee5b9615',
    messagingSenderId: '1000701991568',
    projectId: 'expense-tracker-343a3',
    storageBucket: 'expense-tracker-343a3.appspot.com',
    iosBundleId: 'com.strikle.expense.tracker.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGxEHNPllFoPGSQZyKdf5tvnODsLxQyfc',
    appId: '1:1000701991568:ios:54b2dde1db01ecee5b9615',
    messagingSenderId: '1000701991568',
    projectId: 'expense-tracker-343a3',
    storageBucket: 'expense-tracker-343a3.appspot.com',
    iosBundleId: 'com.strikle.expense.tracker.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOU9abGVPM_dfLbEkqlXmNXXN_gxZssus',
    appId: '1:1000701991568:web:c4fc521e3091d6345b9615',
    messagingSenderId: '1000701991568',
    projectId: 'expense-tracker-343a3',
    authDomain: 'expense-tracker-343a3.firebaseapp.com',
    storageBucket: 'expense-tracker-343a3.appspot.com',
    measurementId: 'G-GVXR8PELQ6',
  );
}
